#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 3.0.dev1.build{build}

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda3
      ARCH: "32"
      CONDARC: .condarc-32
      REQUIREMENTS: requirements-conda-dev-32.txt
      
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda3-x64
      ARCH: "64"
      CONDARC: .condarc
      REQUIREMENTS: requirements-conda-dev.txt

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda update python
  - conda update --all
  - conda info
  - conda create -n _dtocean_core python=%PYTHON_VERSION% pip
  - conda activate _dtocean_core
  - copy %CONDARC% %CONDA_PREFIX%\\.condarc
  - >
    conda install "polite>=0.10,<1"
    "aneris>=0.11.1,<1"
    "dtocean-economics>=2.0.0,<3"
    "dtocean-electrical>=2.0.0,<3"
    "dtocean-environment>=2.0.0,<3"
    "dtocean-hydrodynamics>=3.0.0,<4"
    "dtocean-installation>=2.0.0,<3"
    "dtocean-logistics>=3.0.0,<4"
    "dtocean-maintenance>=3.0.0,<4"
    "dtocean-moorings>=2.0.0,<3"
    "dtocean-reliability>=3.0.0,<4"
  - python setup.py bootstrap
  - conda install --file %REQUIREMENTS%
  - chcp 65001
  - set PYTHONIOENCODING=utf-8
  - pip install -e .
  - conda install mock pytest pytest-cov=2.5.1 pytest-mock

build: off

test_script:
  - python setup.py test -a "--cov dtocean_core"

after_test:
 - pip install codecov
 - codecov
