---
# Required
root_project_path:
worker_dir:
n_threads:
base_penalty: 1.
objective: "project.lcoe_median"

# Optional
clean_existing_dir:         # 'true' will empty the worker_dir if it exists
popsize:                    # number of sample points per iteration [default: 4 + int(3 * np.log(N))]
max_simulations:            # quit after n simulations (following an iteration)
timeout:                    # quit after t seconds (following an iteration)
tolfun:                     # tolerance in function value for termination [default: 1e-11]
min_evals:                  # minimum number of maintenance data points for noise handling
max_evals:                  # maximum number of maintenance data points for noise handling [default: 8]
max_resample_factor:        # multiplied by popsize to give maximum number of resample loops [default: 20]
                            # can give "auto" followed by number of iterations to record max resamples
log_valid_solutions: true   # Show valid solutions found by the optimiser in the logging [default: false])

# Do not modify
results_params:
  - project.number_of_devices
  - project.annual_energy
  - project.q_factor
  - project.capex_total
  - project.capex_breakdown
  - project.lifetime_opex_mean
  - project.lifetime_energy_mean
  - project.lcoe_median
  - project.lcoe_mean

# Parameter specification
parameters:
    grid_orientation:
      range:
        type: fixed
        min: -90.
        max: 90.
    delta_row:
      range:
        type: multiplier
        variable: device.minimum_distance_x
        min_multiplier: 1.
        max_multiplier: 2.
    delta_col:
      range:
        type: multiplier
        variable: device.minimum_distance_y
        min_multiplier: 1.
        max_multiplier: 2.
    n_nodes:
      range:
        type: fixed
        min: 1
        max: 20
      x0: 15
    t1:
      range:
        type: fixed
        min: 0.
        max: 1.
    t2:
      range:
        type: fixed
        min: 0.
        max: 1.

